### ISSUE TITLE
Using your code

### ISSUE THREAD

**Issue by wilburforce83** [dvernooy/ErgWare#2]
Hi there, 

I was wondering if you would mind me using your base code (calculations / assumptions etc) in order to build a nodeJS application for a raspberry pi; I am looking at trying to create an easily replicable unit for myself and others to add to their openergos.

My plan is to build a nice looking GUI front end, with similar sensors connecting to the GPIO's then use your equations to generate the data feeds in a front end, with perhaps a syncing method to Garmin connect or something.

I will of course credit you for doing all the hard work!

**Comment by dvernooy** [comment]
Hi - of course this would be fine! (Its the whole point of open source). I know the project I have posted is not super easy to replicate & a raspberry pi or arduino-based solution might be easier. Let me know how I can help - I'm more than willing to pitch in if you run into any issues.

-Dave
